Добавил title
vinokurov-and/kguProject pull request #24
Opened 2023-10-22 17:31 UTC by DamSnes

2023-10-23 18:52 UTC, vinokurov-and requested changes

2023-10-23 18:52 UTC, vinokurov-and commented on package.json
> +    "@fontsource/roboto": "^5.0.8",
Зачем эта библиотека нужна? Если нигде не используется, то ее надо удалить

2023-10-23 18:52 UTC, vinokurov-and commented on package.json
> +    "react-scripts": "^5.0.1"
эта библиотека как тут оказалась? Она должна быть в "dependencies" разделе

2023-10-23 19:01 UTC, vinokurov-and requested changes

2023-10-23 19:01 UTC, vinokurov-and commented on package.json
> +    "@material-ui/core": "^4.12.4",
Почему 4 версия material ui? сейчас последняя это 5 версия

2023-10-24 17:51 UTC, DamSnes commented
Поправил

2023-10-27 09:08 UTC, vinokurov-and commented
Принято

2023-10-27 09:09 UTC, vinokurov-and commented
Теперь надо разрулить конфликты:

Тут описано как это делать, если не понятно будет совсем что делать, то напиши сюда или в личку

<img width="862" alt="image" src="https://github.com/vinokurov-and/kguProject/assets/48560509/ae495107-b539-4ad7-8290-aa0b12a67bee">

2023-11-03 20:34 UTC, vinokurov-and approved these changes

2023-11-03 20:34 UTC, merged