Пробный вариант кнопки назад
vinokurov-and/kguProject pull request #31
Opened 2023-11-07 10:03 UTC by sublustrume

2023-11-07 10:05 UTC, sublustrume commented
Все вроде работает, но если нажать на саму кнопку, появляется ошибка. Не знаю, норма это или нет

2023-11-18 18:54 UTC, vinokurov-and requested changes

2023-11-18 18:54 UTC, vinokurov-and commented on src/components/BackButton/BackButton.jsx
> +import {useNavigate, useLocation} from "react-router-dom";
убрать useLocation

2023-11-18 18:54 UTC, vinokurov-and commented on src/components/BackButton/BackButton.jsx
> +    // const location = useLocation();
Убрать комментарий

2023-11-18 18:54 UTC, vinokurov-and commented on src/components/BackButton/BackButton.jsx
> +        <button className="backButton" onClick={() => hist.goBack()}>
заменить hist.goBack() на hist(-1);

goBack нет такого метода. 

-1 значит вернуться на шаг назад

2023-12-22 20:39 UTC, vinokurov-and approved these changes

2023-12-22 20:39 UTC, merged